version: 2 # use CircleCI 2.0
jobs: # a collection of steps
  build: # runs not using Workflows must have a `build` job as entry point
    working_directory: ~/gls # directory where steps will run
    docker: # run the steps with Docker
      - image: tabookey/eth-tools:solc-5.5 # solc5.5, NO truffle/ganache (npm-install'ed locally)A

    steps: # a collection of executable commands
      - checkout # special step to check out source code to working directory
      
      - restore_cache: # special step to restore the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm-wee
          command: npm install
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules

      - restore_cache: # special step to restore the dependency cache
          key: dependency-cache-go-get
      - run:
          name: preload go-sources
          command: make -C server go-get
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-go-get
          paths:
            - ./server/src/github.com/ethereum

      - run:
          name: compile
          command: make

      - run:
          name: lint
          command: npm run lint

      - run: # run tests
          name: test
          command: npm test | tee test-results.log

      - store_artifacts: # special step to save test results as as artifact
          path: test-results.xml
          prefix: tests
      - store_test_results: # special step to upload test results for display in Test Summary
          path: test-results.log

#too much noise..
#notify:
#  webhooks:
#    - url: https://twist.com/integrations/circleci/from_circleci?install_id=85424&post_data_url=https%3A%2F%2Ftwist.com%2Fapi%2Fv3%2Fintegration_incoming%2Fpost_data%3Finstall_id%3D85424%26install_token%3D85424_0aad1ece9d2470896c9142aae3440b5b
