version: '3'

services:
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    restart: always
    environment:
      DOMAINS: '${HOST} -> http://gsn'
      STAGE: 'production'

  gsn:
    image: opengsn/jsrelay:${DOCKERTAG}
    restart: always
    ports:
      - '8090:80' #needed for debugging without https frontend

    # creates a mapped volume so that relay server will keep keys outside of the container.
    # can be left out, to keep private-key inside the docker.
    volumes:
      - ./gsndata:/app/data
      - ./config:/app/config

    environment:
      url: https://${HOST}
      port: 80
      workdir: /app/data
      config: /app/config/gsn-relay-config.json
